version: 2.1

orbs:
  python: circleci/python@2.1.1

workflows:
  Tests:
    jobs:
      - test:
          name: test_on_linux_cpu
          executor: linux_cpu

executors:
  linux_cpu:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
  linux_gpu:
    machine:
      image: ubuntu-2004-cuda-11.6:2022.09.1
    resource_class: gpu.nvidia.medium
  mac_m1:
    macos:
      xcode: 14.3.1
    resource_class: macos.m1.large.gen1

jobs:
  test:
    parameters:
      executor:
        default: linux_cpu
        type: string
    executor: << parameters.executor >>
    resource_class: large
    steps:
      - checkout
      - run:
          name: Set up Python 3.10
          command: |
            pyenv install 3.10.6
            pyenv global 3.10.6
      - python/install-packages:
          args: wait-for-it
          pkg-manager: pip
          pip-dependency-file: requirements-test.txt
      - run:
          name: Setup environment
          command: python launch.py --skip-torch-cuda-test --exit
          environment:
            PIP_DISABLE_PIP_VERSION_CHECK: "1"
            PIP_PROGRESS_BAR: "off"
            TORCH_INDEX_URL: https://download.pytorch.org/whl/cpu
            WEBUI_LAUNCH_LIVE_OUTPUT: "1"
            PYTHONUNBUFFERED: "1"
      - run:
          name: Start test server
          command: >
            python -m coverage run
            --data-file=.coverage.server
            launch.py
            --skip-prepare-environment
            --skip-torch-cuda-test
            --test-server
            --do-not-download-clip
            --no-half
            --disable-opt-split-attention
            --use-cpu all
            --api-server-stop
            2>&1 | tee output.txt &
      - run:
          name: Run tests
          command: |
            wait-for-it --service 127.0.0.1:7860 -t 600
            sleep 10
            python -m pytest -vv --junitxml=test/results.xml --cov . --cov-report=xml --verify-base-url test
      - run:
          name: Kill test server
          command: curl -vv -XPOST http://127.0.0.1:7860/sdapi/v1/server-stop && sleep 10
          when: always
      - run:
          name: Show coverage
          command: |
            python -m coverage combine .coverage*
            python -m coverage report -i
            python -m coverage html -i
      - store_artifacts:
          name: Upload main app output
          path: output.txt
          destination: output
          when: always
      - store_artifacts:
          name: Upload coverage HTML
          path: htmlcov
          destination: htmlcov
          when: always